// Generated by gencpp from file tut/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TUT_MESSAGE_ADDTWOINTS_H
#define TUT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <tut/AddTwoIntsRequest.h>
#include <tut/AddTwoIntsResponse.h>


namespace tut
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace tut


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tut::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tut::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::tut::AddTwoInts > {
  static const char* value()
  {
    return "tut/AddTwoInts";
  }

  static const char* value(const ::tut::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tut::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::tut::AddTwoInts >
template<>
struct MD5Sum< ::tut::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tut::AddTwoInts >::value();
  }
  static const char* value(const ::tut::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tut::AddTwoIntsRequest> should match
// service_traits::DataType< ::tut::AddTwoInts >
template<>
struct DataType< ::tut::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tut::AddTwoInts >::value();
  }
  static const char* value(const ::tut::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tut::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::tut::AddTwoInts >
template<>
struct MD5Sum< ::tut::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tut::AddTwoInts >::value();
  }
  static const char* value(const ::tut::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tut::AddTwoIntsResponse> should match
// service_traits::DataType< ::tut::AddTwoInts >
template<>
struct DataType< ::tut::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tut::AddTwoInts >::value();
  }
  static const char* value(const ::tut::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUT_MESSAGE_ADDTWOINTS_H
